version: '3.8'
services:
  backend:
    build: ./be
    ports:
      - "5031:5031"
    volumes:
      - ./be:/app
    working_dir: /app
    command: ["node", "server.js"]
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: pwd123456
      DB_NAME: swdb

  frontend:
    build: ./fe
    ports:
      - "3000:80"
  
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd123456
      MYSQL_DATABASE: swdb
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h" , "localhost", "-pwd123456"]
      interval: 5s
      timeout: 3s
      retries: 5
